Repository absmach/magistrala, pull requests merged in 2019-02, with the labels that each got.

#580 MF-571 Add things and channels lists to Connection module
  ui/elm.json
  ui/src/Channel.elm
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/Main.elm
  ui/src/Thing.elm
Labels: feature

#599 NOISSUE -update message module
  ui/src/Channel.elm
  ui/src/Message.elm
Labels: UI, feature

#604 Remove logout button and add logout header
  ui/src/Channel.elm
  ui/src/Main.elm
  ui/src/User.elm
Labels: UI

#606 MF-571 - Pagination
  ui/src/Channel.elm
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/Message.elm
  ui/src/Thing.elm
Labels: UI, feature

#607 NOISSUE - Add bootstrap cards in version view
  ui/css/mainflux.css
  ui/src/Channel.elm
  ui/src/Connection.elm
  ui/src/Main.elm
  ui/src/Version.elm
Labels: UI

#614 MF-571 - Add dashboard
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/Main.elm
  ui/src/Message.elm
  ui/src/Thing.elm
  ui/src/User.elm
  ui/src/Version.elm
Labels: UI, feature, work-in-progress
