Repository absmach/magistrala, pull requests merged in 2019-03, with the labels that each got.

#620 MF-571 - UI Thing module with modals
  ui/src/Helpers.elm
  ui/src/Main.elm
  ui/src/Thing.elm
Labels: UI, enhancement, feature

#621 MF-571 - UI channel modals
  ui/src/Channel.elm
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/HttpMF.elm
  ui/src/Message.elm
  ui/src/ModalMF.elm
  ui/src/Thing.elm
Labels: UI, feature

#623 MF-571 - Fix user login and refactor User
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/HttpMF.elm
  ui/src/Main.elm
  ui/src/Message.elm
  ui/src/User.elm
Labels: UI, enhancement

#654 MF-571 - Add Env.elm to set custom base URL
  ui/README.md
  ui/src/Channel.elm
  ui/src/Connection.elm
  ui/src/Env.elm
  ui/src/HttpMF.elm
  ui/src/Main.elm
  ui/src/Message.elm
  ui/src/Thing.elm
  ui/src/User.elm
  ui/src/Version.elm
Labels: UI, enhancement

#672 MF-661 - Bootstrap pagination in UI
  message.pb.go
  ui/README.md
  ui/css/mainflux.css
  ui/src/Channel.elm
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/Message.elm
  ui/src/Thing.elm
Labels: UI
