Repository absmach/magistrala, pull requests merged in 2019-04, with the labels that each got.

#679 MF-673 - Fix offset calculation after deleting thing or channel
  ui/src/Helpers.elm
Labels: UI

#678 MF-662 - Change menu style
  ui/css/mainflux.css
  ui/src/Channel.elm
  ui/src/Helpers.elm
  ui/src/Main.elm
Labels: UI

#696 NOISSUE - Remove debugging message from response of handle error function
  ui/src/Error.elm
Labels: UI

#719 NOISSUE - Improve UI styling
  ui/css/mainflux.css
  ui/src/Channel.elm
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/Main.elm
  ui/src/Message.elm
  ui/src/Thing.elm
Labels: UI

#721 Fix things and channels metadata create and edit & remove thing type
  ui/Makefile
  ui/README.md
  ui/docker/Dockerfile
  ui/index.html
  ui/src/Channel.elm
  ui/src/Helpers.elm
  ui/src/JsonMF.elm
  ui/src/Main.elm
  ui/src/Ports.elm
  ui/src/Thing.elm
Labels: UI, bug, work-in-progress

#725 Fix .dockerignore file by removing index.html
  ui/.dockerignore
  ui/docker/Dockerfile
  ui/src/JsonMF.elm
Labels: UI, bug

#728 Add UI websocket open/close and send/receive
  ui/index.html
  ui/src/Connection.elm
  ui/src/Helpers.elm
  ui/src/Main.elm
  ui/src/Message.elm
  ui/src/Ports.elm
  ui/src/Websocket.js
Labels: UI, feature
